src/Entity/Pair.php
<?php

namespace App\Entity;

use App\Repository\PairRepository;
use Carbon\Carbon;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PairRepository::class)
 */
class Pair
{

    public function __construct()
    {
        $this->createdAt = new DateTime();
    }
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pairs")
     */
    private $candidate;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isPositionLiked;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isCandidateLiked;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity=Vacancy::class, inversedBy="pairs")
     */
    private $vacancy;

    /**
     * @ORM\ManyToOne(targetEntity=Resume::class, inversedBy="pairs")
     */
    private $resume;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCandidate(): ?User
    {
        return $this->candidate;
    }

    public function setCandidate(?User $candidate): self
    {
        $this->candidate = $candidate;

        return $this;
    }

    public function getIsPositionLiked(): ?bool
    {
        return $this->isPositionLiked;
    }

    public function setIsPositionLiked(bool $isPositionLiked): self
    {
        $this->isPositionLiked = $isPositionLiked;

        return $this;
    }

    public function getIsCandidateLiked(): ?bool
    {
        return $this->isCandidateLiked;
    }

    public function setIsCandidateLiked(bool $isCandidateLiked): self
    {
        $this->isCandidateLiked = $isCandidateLiked;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function getCreatedAtForHumans(): string
    {
        $date = Carbon::parse($this->createdAt);
        return $date->diffForHumans();
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getVacancy(): ?Vacancy
    {
        return $this->vacancy;
    }

    public function setVacancy(?Vacancy $vacancy): self
    {
        $this->vacancy = $vacancy;

        return $this;
    }

    public function getResume(): ?Resume
    {
        return $this->resume;
    }

    public function setResume(?Resume $resume): self
    {
        $this->resume = $resume;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */


class User implements UserInterface
{

    const ROLE_EMPLOYER = 'ROLE_EMPLOYER';
    const ROLE_EMPLOYEE = 'ROLE_EMPLOYEE';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Resume::class, mappedBy="owner")
     */
    private $resumes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phoneNumber;

    /**
     * @ORM\OneToMany(targetEntity=Pair::class, mappedBy="candidate")
     */
    private $pairs;

    /**
     * @ORM\OneToMany(targetEntity=Vacancy::class, mappedBy="owner")
     */
    private $getAuthouredVacancies;

    public function __construct()
    {
        $this->resumes = new ArrayCollection();
        $this->pairs = new ArrayCollection();
        $this->getAuthouredVacancies = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }


    public function getAccountType(): string
    {
        $roles = $this->roles;
        foreach ($roles as $role) {
            return match ($role) {
                self::ROLE_EMPLOYER => self::ROLE_EMPLOYER,
                self::ROLE_EMPLOYEE => self::ROLE_EMPLOYEE
            };
        }
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }


    /**
     * @return Collection|Resume[]
     */
    public function getResumes(): Collection
    {
        return $this->resumes;
    }

    public function addResume(Resume $resume): self
    {
        if (!$this->resumes->contains($resume)) {
            $this->resumes[] = $resume;
            $resume->setOwner($this);
        }

        return $this;
    }

    public function removeResume(Resume $resume): self
    {
        if ($this->resumes->removeElement($resume)) {
            // set the owning side to null (unless already changed)
            if ($resume->getOwner() === $this) {
                $resume->setOwner(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    /**
     * @return Collection|Pair[]
     */
    public function getPairs(): Collection
    {
        return $this->pairs;
    }

    public function addPair(Pair $pair): self
    {
        if (!$this->pairs->contains($pair)) {
            $this->pairs[] = $pair;
            $pair->setCandidate($this);
        }

        return $this;
    }

    public function removePair(Pair $pair): self
    {
        if ($this->pairs->removeElement($pair)) {
            // set the owning side to null (unless already changed)
            if ($pair->getCandidate() === $this) {
                $pair->setCandidate(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Vacancy[]
     */
    public function getGetAuthouredVacancies(): Collection
    {
        return $this->getAuthouredVacancies;
    }

    public function addGetAuthouredVacancy(Vacancy $getAuthouredVacancy): self
    {
        if (!$this->getAuthouredVacancies->contains($getAuthouredVacancy)) {
            $this->getAuthouredVacancies[] = $getAuthouredVacancy;
            $getAuthouredVacancy->setOwner($this);
        }

        return $this;
    }

    public function removeGetAuthouredVacancy(Vacancy $getAuthouredVacancy): self
    {
        if ($this->getAuthouredVacancies->removeElement($getAuthouredVacancy)) {
            // set the owning side to null (unless already changed)
            if ($getAuthouredVacancy->getOwner() === $this) {
                $getAuthouredVacancy->setOwner(null);
            }
        }

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Experience;
use App\Entity\Pair;
use App\Entity\Resume;
use App\Entity\Vacancy;
use App\Form\ExperienceFormType;
use App\Form\PairFormType;
use App\Form\QualificationFormType;
use App\Form\ResumeFormType;
use App\Repository\ExperienceRepository;
use App\Repository\PairRepository;
use App\Repository\QualificationRepository;
use App\Repository\ResumeRepository;
use App\Repository\VacancyRepository;
use App\Service\FlashMessageService;
use App\Service\PdfGeneratorSerivce;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;


class UserController extends AbstractController
{
  public function __construct(
    private Security $security,
    private PdfGeneratorSerivce $pdfGenerator,
    private VacancyRepository $vacancyRepository,
    private PairRepository $pairRepository,
    private ResumeRepository $resumeRepository,
    private ExperienceRepository $experienceRepository,
    private QualificationRepository $qualificationRepository
  ) {
  }

  #[Route('/dashboard', name: 'user.dashboard')]
  public function register(Request $request): Response
  {
    /**
     * @var User $user
     */
    $user = $this->security->getUser();
    $resume = $user->getResumes()->first();


    if ($resume) {
      $result = $this->vacancyRepository->findUnpairedVacancyByUserResume($resume);
    }

    $vacancy = $result['vacancy'] ?? null;
    $count = $result['count'] ?? 0;
    /**
     * @var FormInterface $pairForm
     */
    $pairForm = $this->createForm(PairFormType::class);
    $pairForm->handleRequest($request);

    if ($pairForm->isSubmitted() && $pairForm->isValid()) {


      $isLiked = $pairForm->get('likeBtn')->isClicked();
      $resume = $pairForm->get('resume')->getData();

      dump($request);
      die;

      $this->pairRepository->create($user, $vacancy, $isLiked, $resume);
      return new RedirectResponse($this->generateUrl('user.dashboard'));
    }

    return $this->render('user/dashboard.html.twig', [
      'user' => $user,
      'vacancy' => $vacancy,
      'count' => $count,
      'pairForm' => $pairForm->createView()
    ]);
  }

  #[Route('/account', name: 'user.account')]
  public function account(): Response
  {
    $user = $this->security->getUser();
    return $this->render('user/account.html.twig', [
      'user' => $user
    ]);
  }

  #[Route('/matches', name: 'user.matches')]
  public function matches(): Response
  {
    /**
     * @var User $user
     */
    $user = $this->security->getUser();
    $matches = $this->pairRepository->getCandidateMatches($user);
    return $this->render('user/matches.html.twig', [
      'user' => $user,
      'pairs' => $matches
    ]);
  }
}

templates/user/account.html.twig
{% extends 'base.html.twig' %}

{% block title %}account{% endblock %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
            {{ user.name }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user/dashboard.html.twig
{% extends 'base.html.twig' %} {% block title %}Dashboard{% endblock %} {% block
body %}
<div class="row justify-content-center">
  <div class="col-md-8">
    {% if vacancy %}
    <div class="between mb-3">
      <h3>
        <span
          data-bs-toggle="tooltip"
          data-bs-placement="bottom"
          title="matched vacancies"
          class="badge rounded-pill bg-secondary"
          ><i class="bi bi-briefcase-fill"></i>
          {{ count }}
        </span>
      </h3>
      <div
        class="w-25"
        data-bs-toggle="tooltip"
        data-bs-placement="bottom"
        title="selected resume"
      >
        {{ form_row(pairForm.resume) }}
      </div>
    </div>
    {% endif %} {% if vacancy %}
    {{ form_start(pairForm) }}
    <div class="card">
      <div class="card-header bg-transparent between">
        <div>
          <h3 class="card-title m-0">{{ vacancy.position }}</h3>
          <div>{{ vacancy.category.title }}</div>
        </div>
        <div>
          <span
            class="badge rounded-pill bg-dark"
            data-bs-toggle="tooltip"
            data-bs-placement="bottom"
            title="years experience"
          >
            <i class="bi bi-star-fill"></i> {{ vacancy.yearsExperience }}</span
          >
        </div>
      </div>
      <div class="card-body vacancyDisplay">
        {{ vacancy.description }}
      </div>
      <div class="card-footer bg-transparent d-flex justify-content-between">
        <div>{{ vacancy.createdAtForHumans }}</div>
      </div>
    </div>

    <div class="d-flex justify-content-between mt-3">
      <div
        data-bs-toggle="tooltip"
        data-bs-placement="bottom"
        title="not interested"
      >
        {{ form_row(pairForm.nextBtn) }}
      </div>
      <div data-bs-toggle="tooltip" data-bs-placement="bottom" title="match">
        {{ form_row(pairForm.likeBtn) }}
      </div>
    </div>

    {{ form_end(pairForm) }}

    {% elseif app.user.resumes|length == 0 %}
    <div class="card">
      <div class="card-body">
        <div class="text-center text-muted mb-3">
          <h5>No resume found</h5>
          create resume to be matched with vacancies
        </div>
        <div class="text-center">
          <a
            class="btn btn-outline-dark"
            href="{{ path('user.resume.create') }}"
          >
            Create resume
          </a>
        </div>
      </div>
    </div>
    {% else %}
    <div class="card">
      <div class="card-body">
        <div class="text-center text-muted mb-3">
          <h5>No jobs found</h5>
          No vacancies matched your resume, try again later.
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/user/jobs.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard{% endblock %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header bg-transparent">Searching</div>
            <div class="card-body">
              You are looking for a job now...
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user/matches.html.twig
{% extends 'base.html.twig' %} {% block title %}Dashboard{% endblock %} {% block
body %}
<div class="row justify-content-center">
  <div class="col-md-8">
    <ul class="list-group mb-3">
      <li class="list-group-item between">
        <div class="fs-4">Matches</div>
      </li>
      {% for match in pairs %}
      <li class="list-group-item d-flex justify-content-between">
        <div>
          <div>{{ match.vacancy.owner.name }}</div>
          <h5 class="m-0">
            {{ match.vacancy.position }}
          </h5>
          {{ match.vacancy.category.title }}
        </div>
        <div>{{ match.createdAtForHumans }}</div>
      </li>
      {% else %}
      <li class="list-group-item text-center p-3">
        <div class="card">
          <div class="card-body">
            <div class="text-center text-muted mb-3">
              <h5>Sorry :/</h5>
              No matches found yet. Keep trying, you'll find your match.
            </div>
          </div>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

templates/user/resume.html.twig
{% extends 'base.html.twig' %} {% block title %}Dashboard{% endblock %} {% block
body %}

<style>
  section.divider {
    border-bottom: 1px solid #cccccc;
  }
</style>

<div class="row justify-content-center">
  <div class="col-md-4">
    <h1 class="m-0">{{ user.name }}</h1>
    <ul class="list-group list-group-flush">
      <li class="list-group-item px-0">
        {{ user.email }}
      </li>
      <li class="list-group-item px-0">
        {{ user.phoneNumber }}
      </li>
    </ul>
  </div>
  <div class="col-md-8">
    <section class="divider mb-3">
      <div class="mb-3 d-flex justify-content-between align-items-center">
        <div>
          <h1 class="m-0">{{ resume.position }}</h1>
          <div>{{ resume.category.title }}</div>
        </div>
      </div>
    </section>

    <div class="text-end">
      <div class="btn-group mb-3" role="group" aria-label="Basic example">
        <a
          class="btn btn-outline-dark"
          href="{{ path('user.resume.edit', { id: resume.id }) }}"
          data-bs-toggle="tooltip"
          data-bs-placement="bottom"
          title="Edit"
        >
          <i class="bi bi-pen"></i>
        </a>
        <a
          class="btn btn-outline-dark"
          href="{{ path('user.resume.download', { id: resume.id }) }}"
          data-bs-toggle="tooltip"
          data-bs-placement="bottom"
          title="Download"
        >
          <i class="bi bi-download"></i>
        </a>
      </div>
    </div>

    <section class="divider mb-3">
      <h5 class="m-0">Statement</h5>
      <div class="card-body px-0 pre">
        {{ resume.statement }}
      </div>
    </section>

    <section class="divider mb-3">
      <h5>Experience</h5>
      <ul class="list-group list-group-flush">
        {% for experience in resume.experiences %}
        <li class="list-group-item px-0">
          <span class="fw-bold">{{ experience.title }} </span> |
          {{ experience.company }}
          {% if experience.isCurrent %}
          <span
            class="badge rounded-pill bg-success"
            data-bs-toggle="tooltip"
            data-bs-placement="bottom"
            title="current position"
          >
            <i class="bi bi-check"></i>
          </span>
          {% endif %}
          <div>
            {{ experience.getDuration }}
          </div>
        </li>
        {% else %}
        <li class="list-group-item">no experience found</li>
        {% endfor %}
      </ul>
    </section>

    <section class="mb-3">
      <h5>Education</h5>
      <ul class="list-group list-group-flush">
        {% for qualification in resume.qualifications %}
        <li class="list-group-item px-0">
          <span class="fw-bold">{{ qualification.title }} </span> |
          {{ qualification.issuer }} - {{ qualification.getFormatedCreateAt }}
        </li>
        {% else %}
        <li class="list-group-item">no qualifications found</li>
        {% endfor %}
      </ul>
    </section>

    <div class="d-flex justify-content-between">
      <div></div>
      <div><i class="bi bi-clock"></i> {{ resume.getCreateAtForHumans }}</div>
    </div>
  </div>
</div>
{% endblock %}